import { createCipheriv, createDecipheriv, createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { cookies } from 'next/headers';
import type { CustomerAccountSession } from './customer-account-types';

const SESSION_COOKIE = 'shopifyCustomerSession';
const STATE_COOKIE = 'shopifyCustomerState';
const VERIFIER_COOKIE = 'shopifyCustomerVerifier';
const NONCE_COOKIE = 'shopifyCustomerNonce';
const SESSION_MAX_AGE = 60 * 60 * 24 * 30;
const OAUTH_MAX_AGE = 60 * 10;
const cookieOptions = { httpOnly: true, sameSite: 'lax' as const, secure: process.env.NODE_ENV === 'production', path: '/' };

type Discovery = { authorization_endpoint: string; token_endpoint: string; end_session_endpoint?: string };
type ApiDiscovery = { graphql_api: string };

function shopDomain() { const value = process.env.VTBSJMYH_SHOPIFY_STORE_DOMAIN?.trim(); if (!value) throw new Error('Shopify customer authentication is not configured.'); return value.replace(/^https?:\/\//, '').replace(/\/$/, ''); }
function clientId() { const value = process.env.SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_ID?.trim(); if (!value) throw new Error('Shopify customer authentication is not configured.'); return value; }
function callbackUrl() { return process.env.SHOPIFY_CUSTOMER_ACCOUNT_CALLBACK_URL?.trim() || `${process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, '') || 'https://house-of-aristocrat.vercel.app'}/api/customer-auth/callback`; }
function key() { const value = process.env.SHOPIFY_CUSTOMER_ACCOUNT_SESSION_SECRET?.trim() || process.env.SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_SECRET?.trim(); if (!value) throw new Error('Shopify customer session encryption is not configured.'); return createHash('sha256').update(value).digest(); }
function encrypt(value: string) { const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', key(), iv); const content = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return Buffer.concat([iv, cipher.getAuthTag(), content]).toString('base64url'); }
function decrypt(value: string) { const content = Buffer.from(value, 'base64url'); const decipher = createDecipheriv('aes-256-gcm', key(), content.subarray(0, 12)); decipher.setAuthTag(content.subarray(12, 28)); return Buffer.concat([decipher.update(content.subarray(28)), decipher.final()]).toString('utf8'); }
function random() { return randomBytes(32).toString('base64url'); }
function challenge(verifier: string) { return createHash('sha256').update(verifier).digest('base64url'); }
function same(a: string, b: string) { const left = Buffer.from(a); const right = Buffer.from(b); return left.length === right.length && timingSafeEqual(left, right); }

export function hasCustomerAccountConfig() { return Boolean(process.env.SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_ID?.trim() && process.env.VTBSJMYH_SHOPIFY_STORE_DOMAIN?.trim() && (process.env.SHOPIFY_CUSTOMER_ACCOUNT_SESSION_SECRET?.trim() || process.env.SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_SECRET?.trim())); }
export async function getCustomerDiscovery(): Promise<Discovery> { const override = process.env.SHOPIFY_CUSTOMER_ACCOUNT_AUTHORIZATION_URL && process.env.SHOPIFY_CUSTOMER_ACCOUNT_TOKEN_URL ? { authorization_endpoint: process.env.SHOPIFY_CUSTOMER_ACCOUNT_AUTHORIZATION_URL, token_endpoint: process.env.SHOPIFY_CUSTOMER_ACCOUNT_TOKEN_URL, end_session_endpoint: process.env.SHOPIFY_CUSTOMER_ACCOUNT_LOGOUT_URL } : null; if (override) return override; const response = await fetch(`https://${shopDomain()}/.well-known/openid-configuration`, { cache: 'no-store' }); if (!response.ok) throw new Error('Customer authentication discovery failed.'); const data = await response.json() as Discovery; if (!data.authorization_endpoint || !data.token_endpoint) throw new Error('Customer authentication discovery was incomplete.'); return data; }
export async function getCustomerApiEndpoint() { const override = process.env.SHOPIFY_CUSTOMER_ACCOUNT_API_URL?.trim(); if (override) return override; const response = await fetch(`https://${shopDomain()}/.well-known/customer-account-api`, { cache: 'no-store' }); if (!response.ok) throw new Error('Customer API discovery failed.'); const data = await response.json() as ApiDiscovery; if (!data.graphql_api) throw new Error('Customer API discovery was incomplete.'); return data.graphql_api; }

export async function createCustomerAuthorizationUrl() { const discovery = await getCustomerDiscovery(); const state = random(); const verifier = random(); const nonce = random(); const store = await cookies(); store.set(STATE_COOKIE, state, { ...cookieOptions, maxAge: OAUTH_MAX_AGE }); store.set(VERIFIER_COOKIE, verifier, { ...cookieOptions, maxAge: OAUTH_MAX_AGE }); store.set(NONCE_COOKIE, nonce, { ...cookieOptions, maxAge: OAUTH_MAX_AGE }); const url = new URL(discovery.authorization_endpoint); url.searchParams.set('scope', 'openid email customer-account-api:full'); url.searchParams.set('client_id', clientId()); url.searchParams.set('response_type', 'code'); url.searchParams.set('redirect_uri', callbackUrl()); url.searchParams.set('state', state); url.searchParams.set('nonce', nonce); url.searchParams.set('code_challenge', challenge(verifier)); url.searchParams.set('code_challenge_method', 'S256'); return url.toString(); }

export async function exchangeCustomerCode(code: string, returnedState: string) { const store = await cookies(); const state = store.get(STATE_COOKIE)?.value; const verifier = store.get(VERIFIER_COOKIE)?.value; store.delete(STATE_COOKIE); store.delete(VERIFIER_COOKIE); store.delete(NONCE_COOKIE); if (!state || !verifier || !same(state, returnedState)) throw new Error('Invalid customer authentication state.'); const discovery = await getCustomerDiscovery(); const params = new URLSearchParams({ grant_type: 'authorization_code', client_id: clientId(), code, redirect_uri: callbackUrl(), code_verifier: verifier }); const headers: HeadersInit = { 'Content-Type': 'application/x-www-form-urlencoded', Origin: new URL(callbackUrl()).origin, 'User-Agent': 'House of Aristocrat Customer Account' }; const secret = process.env.SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_SECRET?.trim(); if (secret) headers.Authorization = `Basic ${Buffer.from(`${clientId()}:${secret}`).toString('base64')}`; const response = await fetch(discovery.token_endpoint, { method: 'POST', headers, body: params, cache: 'no-store' }); if (!response.ok) throw new Error(`Customer token exchange failed with status ${response.status}.`); const data = await response.json() as { access_token?: string; refresh_token?: string; id_token?: string; expires_in?: number }; if (!data.access_token || !data.expires_in) throw new Error('Customer token response was incomplete.'); const session: CustomerAccountSession = { accessToken: data.access_token, refreshToken: data.refresh_token, idToken: data.id_token, expiresAt: Date.now() + data.expires_in * 1000 }; await saveCustomerSession(session); }

export async function getCustomerSession() { const value = (await cookies()).get(SESSION_COOKIE)?.value; if (!value) return null; try { const session = JSON.parse(decrypt(value)) as CustomerAccountSession; return session.expiresAt > Date.now() + 30_000 ? session : null; } catch { return null; } }
export async function saveCustomerSession(session: CustomerAccountSession) { (await cookies()).set(SESSION_COOKIE, encrypt(JSON.stringify(session)), { ...cookieOptions, maxAge: Math.min(SESSION_MAX_AGE, Math.max(60, Math.floor((session.expiresAt - Date.now()) / 1000))) }); }
export async function clearCustomerSession() { const store = await cookies(); store.delete(SESSION_COOKIE); store.delete(STATE_COOKIE); store.delete(VERIFIER_COOKIE); store.delete(NONCE_COOKIE); }
export async function getCustomerLogoutUrl() { const configured = process.env.SHOPIFY_CUSTOMER_ACCOUNT_LOGOUT_URL?.trim(); if (configured) return configured; return (await getCustomerDiscovery()).end_session_endpoint ?? null; }
