'use client';
import { SlidersHorizontal, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import type { CatalogProduct } from '@/types/commerce';
import { CatalogProductCard } from '@/components/product/CatalogProductCard';

const pageSize = 8;
const sortOptions = [['featured', 'Featured'], ['newest', 'Newest'], ['price-low', 'Price: Low to high'], ['price-high', 'Price: High to low'], ['best-selling', 'Best selling']] as const;
export function CatalogGrid({ collection, limit = pageSize }: { collection?: string; limit?: number }) {
  const [products, setProducts] = useState<CatalogProduct[]>([]); const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const values = { category: searchParams.get('category') ?? '', price: searchParams.get('price') ?? '', size: searchParams.get('size') ?? '', color: searchParams.get('color') ?? '', availability: searchParams.get('availability') ?? '', sort: searchParams.get('sort') ?? 'featured', page: Number(searchParams.get('page') ?? 1) };
  useEffect(() => { fetch('/api/catalog').then((response) => response.json()).then(setProducts); }, []);
  const update = (key: string, value: string) => { const params = new URLSearchParams(searchParams.toString()); value ? params.set(key, value) : params.delete(key); if (key !== 'page') params.delete('page'); router.replace(`${pathname}${params.size ? `?${params.toString()}` : ''}`, { scroll: false }); };
  const clear = () => router.replace(pathname, { scroll: false });
  const categories = [...new Set(products.map((product) => product.category))]; const colors = [...new Set(products.flatMap((product) => product.colors))]; const sizes = [...new Set(products.flatMap((product) => product.sizes))];
  const filtered = useMemo(() => { let list = collection && !['New Arrivals', 'Best Sellers', 'Sale'].includes(collection) ? products.filter((product) => product.category === collection) : collection === 'Best Sellers' ? products.filter((product) => product.isBestSeller) : collection === 'Sale' ? products.filter((product) => product.compareAtPrice > product.price) : products; if (values.category) list = list.filter((product) => product.category === values.category); if (values.size) list = list.filter((product) => product.sizes.includes(values.size)); if (values.color) list = list.filter((product) => product.colors.includes(values.color)); if (values.availability) list = list.filter((product) => values.availability === 'in-stock' ? product.inStock : !product.inStock); if (values.price) { const [min, max] = values.price.split('-').map(Number); list = list.filter((product) => product.price >= min && (!max || product.price <= max)); } return [...list].sort((a, b) => values.sort === 'price-low' ? a.price - b.price : values.sort === 'price-high' ? b.price - a.price : values.sort === 'best-selling' ? Number(b.isBestSeller) - Number(a.isBestSeller) || b.rating - a.rating : values.sort === 'newest' ? Number(b.isNew) - Number(a.isNew) || b.id.localeCompare(a.id) : Number(b.isBestSeller) - Number(a.isBestSeller) || b.rating - a.rating); }, [collection, products, values.category, values.size, values.color, values.availability, values.price, values.sort]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / limit)); const currentPage = Math.min(values.page, totalPages); const visible = filtered.slice((currentPage - 1) * limit, currentPage * limit); const hasFilters = Boolean(values.category || values.price || values.size || values.color || values.availability || values.sort !== 'featured');
  return <section className="catalog"><div className="catalog-toolbar"><span>{filtered.length} {filtered.length === 1 ? 'piece' : 'pieces'}</span><div className="sort-control"><SlidersHorizontal size={15} /><label>Sort by <select suppressHydrationWarning value={values.sort} onChange={(event) => update('sort', event.target.value)}>{sortOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div></div><div className="catalog-layout"><aside className="filter-sidebar"><div className="filter-heading"><b>Filters</b>{hasFilters && <button onClick={clear}>Clear all</button>}</div><Filter label="Category" value={values.category} options={categories} onChange={(value) => update('category', value)} /><Filter label="Price" value={values.price} options={[['0-5000', 'Under ?5,000'], ['5000-7000', '?5,000 – ?7,000'], ['7000-0', '?7,000+']]} onChange={(value) => update('price', value)} /><Filter label="Size" value={values.size} options={sizes} onChange={(value) => update('size', value)} /><Filter label="Colour" value={values.color} options={colors} onChange={(value) => update('color', value)} /><Filter label="Availability" value={values.availability} options={[['in-stock', 'In stock'], ['out-of-stock', 'Out of stock']]} onChange={(value) => update('availability', value)} /></aside><div><div className="catalog-grid">{visible.map((product) => <CatalogProductCard key={product.id} product={product} />)}</div>{visible.length === 0 && <div className="empty-results"><p>No pieces match this edit.</p><button suppressHydrationWarning className="button" onClick={clear}>Clear filters</button></div>}{totalPages > 1 && <div className="pagination">{Array.from({ length: totalPages }, (_, index) => <button suppressHydrationWarning key={index} className={currentPage === index + 1 ? 'active' : ''} onClick={() => update('page', String(index + 1))}>{index + 1}</button>)}</div>}</div></div></section>;
}
function Filter({ label, value, options, onChange }: { label: string; value: string; options: (string | readonly [string, string])[]; onChange: (value: string) => void }) { return <details className="filter-group" open><summary>{label}</summary><div>{options.map((option) => { const [optionValue, optionLabel] = Array.isArray(option) ? option : [option, option]; return <label key={optionValue}><input type="radio" name={label} checked={value === optionValue} onChange={() => onChange(value === optionValue ? '' : optionValue)} />{optionLabel}</label>; })}</div></details>; }