'use client';
import Link from 'next/link';
import { Eye, Heart, Star } from 'lucide-react';
import { motion } from 'framer-motion';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { CatalogProduct } from '@/types/commerce';
import { useStore } from '@/context/StoreProvider';
export function CatalogProductCard({ product }: { product: CatalogProduct }) { const { addToCart, formatPrice, toggleWishlist, wishlist } = useStore(); const router = useRouter(); const [status, setStatus] = useState<'idle' | 'adding' | 'added'>('idle'); const saved = wishlist.includes(product.id); const purchasable = Boolean(product.shopifyVariantId && product.shopifyAvailableForSale); const needsOptions = (product.shopifyVariantCount ?? 0) > 1; const discount = Math.round((1 - product.price / product.compareAtPrice) * 100); const add = () => { if (!purchasable || status !== 'idle') return; if (needsOptions) { router.push(`/products/${product.handle}`); return; } setStatus('adding'); window.setTimeout(() => { addToCart(product); setStatus('added'); window.setTimeout(() => setStatus('idle'), 1600); }, 180); }; const buttonLabel = !purchasable ? 'Currently unavailable' : needsOptions ? 'Choose options' : status === 'adding' ? 'Adding…' : status === 'added' ? 'Added' : 'Add to bag'; return <motion.article className="catalog-card" whileHover={{ y: -5 }}><div className="catalog-image"><img src={`/api/assets?file=${encodeURIComponent(product.image)}`} alt={product.title} loading="lazy" /><span className="discount-badge">{discount}% off</span><button type="button" className="heart-button" onClick={() => toggleWishlist(product.id)} aria-label={`Toggle ${product.title} wishlist`}><Heart size={18} fill={saved ? 'currentColor' : 'none'} /></button><div className="card-actions"><Link href={`/products/${product.handle}`} aria-label={`Quick view ${product.title}`}><Eye size={17} /></Link></div><button type="button" className="catalog-add-button" onClick={add} disabled={!purchasable || status !== 'idle'} aria-label={`${buttonLabel}: ${product.title}`}>{buttonLabel}</button></div><div className="catalog-meta"><Link href={`/products/${product.handle}`}><h3>{product.title}</h3></Link><p className="rating"><Star size={13} fill="currentColor" /> {product.rating.toFixed(1)} <span>({product.reviewCount})</span></p><div><b>{formatPrice(product.price)}</b><s>{formatPrice(product.compareAtPrice)}</s></div></div></motion.article>; }
