'use client';
import { Heart, Minus, Plus } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import type { CatalogProduct } from '@/types/commerce';
import { useStore } from '@/context/StoreProvider';
import { CheckoutButton } from '@/components/cart/CheckoutButton';
import { ImageWithLoader } from '@/components/ui/ImageWithLoader';
import { productImageSrc } from '@/lib/catalog/image';
import { isProductWishlisted, productWishlistAliases } from '@/lib/catalog/wishlist';

function selectedValue(product: CatalogProduct, optionName: 'size' | 'color') { const variant = product.variants.find((entry) => entry.availableForSale) ?? product.variants[0]; return variant?.selectedOptions.find((option) => option.name.toLowerCase() === optionName || (optionName === 'color' && option.name.toLowerCase() === 'colour'))?.value ?? (optionName === 'size' ? product.sizes[0] : product.colors[0]) ?? ''; }
export function ProductDetails({ product: initialProduct, related: _related }: { product: CatalogProduct; related: CatalogProduct[] }) {
  const { addToCart, country, formatPrice, wishlist, toggleWishlist } = useStore();
  const [product, setProduct] = useState(initialProduct);
  const [image, setImage] = useState(initialProduct.images[0] ?? initialProduct.image);
  const [size, setSize] = useState(() => selectedValue(initialProduct, 'size'));
  const [color, setColor] = useState(() => selectedValue(initialProduct, 'color'));
  const [quantity, setQuantity] = useState(1);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/catalog?handle=${encodeURIComponent(initialProduct.handle)}&country=${country.code}`, { signal: controller.signal }).then((response) => response.ok ? response.json() as Promise<CatalogProduct> : Promise.reject()).then((next) => { setProduct(next); setImage(next.images[0] ?? next.image); setSize((value) => next.sizes.includes(value) ? value : selectedValue(next, 'size')); setColor((value) => next.colors.includes(value) ? value : selectedValue(next, 'color')); }).catch(() => undefined); return () => controller.abort(); }, [country.code, initialProduct.handle]);
  const variant = useMemo(() => product.variants.find((entry) => entry.selectedOptions.every((option) => { const name = option.name.toLowerCase(); if (name === 'size' && size) return option.value === size; if ((name === 'color' || name === 'colour') && color) return option.value === color; return true; })) ?? product.variants.find((entry) => entry.availableForSale) ?? product.variants[0], [color, product.variants, size]);
  const saved = isProductWishlisted(wishlist, product);
  const purchasable = Boolean(variant?.id && variant.availableForSale);
  const displayPrice = variant?.price ?? product.price;
  const compareAtPrice = variant?.compareAtPrice ?? product.compareAtPrice;
  const currencyCode = variant?.currencyCode ?? product.currencyCode;
  const cartProduct = variant ? { ...product, price: variant.price, compareAtPrice: variant.compareAtPrice, currencyCode: variant.currencyCode, shopifyVariantId: variant.id, shopifyAvailableForSale: variant.availableForSale } : product;
  return <section className="product-view"><div className="gallery"><div className="thumbnails">{product.images.map((entry) => <button key={entry} onClick={() => setImage(entry)}><ImageWithLoader src={productImageSrc(entry)} alt="" fill sizes="76px" /></button>)}</div><div className="main-image"><ImageWithLoader src={productImageSrc(image)} alt={product.imageAlt ?? product.title} fill sizes="(max-width: 768px) 100vw, 55vw" /></div></div><article className="product-info"><p className="eyebrow">{product.category}</p><div className="product-title-row"><h1>{product.title}</h1><button onClick={() => toggleWishlist(product.handle, productWishlistAliases(product))} aria-label="Save product"><Heart fill={saved ? 'currentColor' : 'none'} /></button></div><div className="detail-price"><b>{formatPrice(displayPrice, currencyCode)}</b>{compareAtPrice && compareAtPrice > displayPrice && <s>{formatPrice(compareAtPrice, currencyCode)}</s>}</div>{product.description && <p className="lede">{product.description}</p>}{product.colors.length > 0 && <><p className="eyebrow">Colour — {color}</p><div className="swatches">{product.colors.map((entry) => <button key={entry} className={color === entry ? 'selected' : ''} onClick={() => setColor(entry)}>{entry}</button>)}</div></>}{product.sizes.length > 0 && <><p className="eyebrow">Select size</p><div className="size-row">{product.sizes.map((entry) => <button key={entry} className={size === entry ? 'selected' : ''} onClick={() => setSize(entry)}>{entry}</button>)}</div></>}{product.options.filter((option) => !['size', 'color', 'colour'].includes(option.name.toLowerCase())).map((option) => <div key={option.name}><p className="eyebrow">{option.name}</p><p>{option.values.join(', ')}</p></div>)}<div className="detail-actions"><div className="quantity"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={14} /></button><span>{quantity}</span><button onClick={() => setQuantity(quantity + 1)}><Plus size={14} /></button></div><button className="add-button" onClick={() => Array.from({ length: quantity }).forEach(() => addToCart(cartProduct, { size, color, variantId: variant?.id }))} disabled={!purchasable}>{purchasable ? 'Add to bag' : 'Sold out'}</button></div><CheckoutButton className="buy-now" mode="buy-now" lines={[{ handle: product.handle, title: product.title, variantId: variant?.id, quantity, size, color }]}>Buy now</CheckoutButton><details open><summary>Shipping & returns</summary><p>Shipping, duties and returns are calculated for your market at checkout.</p></details></article></section>;
}
